# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbank.proto\x12\x04\x62\x61nk\"\'\n\x07Request\x12\x0c\n\x04\x62\x61nk\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"*\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t2m\n\x0b\x42\x61nkService\x12,\n\tlendMoney\x12\r.bank.Request\x1a\x0e.bank.Response\"\x00\x12\x30\n\rtransferMoney\x12\r.bank.Request\x1a\x0e.bank.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=20
  _REQUEST._serialized_end=59
  _RESPONSE._serialized_start=61
  _RESPONSE._serialized_end=103
  _BANKSERVICE._serialized_start=105
  _BANKSERVICE._serialized_end=214
# @@protoc_insertion_point(module_scope)
