# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc.bank_pb2 as bank__pb2


class BankServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.lendMoney = channel.unary_unary(
                '/bank.BankService/lendMoney',
                request_serializer=bank__pb2.Request.SerializeToString,
                response_deserializer=bank__pb2.Response.FromString,
                )
        self.transferMoney = channel.unary_unary(
                '/bank.BankService/transferMoney',
                request_serializer=bank__pb2.Request.SerializeToString,
                response_deserializer=bank__pb2.Response.FromString,
                )


class BankServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def lendMoney(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def transferMoney(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'lendMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.lendMoney,
                    request_deserializer=bank__pb2.Request.FromString,
                    response_serializer=bank__pb2.Response.SerializeToString,
            ),
            'transferMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.transferMoney,
                    request_deserializer=bank__pb2.Request.FromString,
                    response_serializer=bank__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bank.BankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BankService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def lendMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.BankService/lendMoney',
            bank__pb2.Request.SerializeToString,
            bank__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def transferMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bank.BankService/transferMoney',
            bank__pb2.Request.SerializeToString,
            bank__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
