version: '3.3'
services:
  lookup:
    container_name: lookup
    environment:
      - PORT=22000
      - LOGLEVEL=INFO
    build: ./Lookup/
    ports:
      - 22000:22000
    restart: unless-stopped
    deploy:
      replicas: 1
  boerse:
    environment:
      - PORT=12345
      - RANDOM_SEED=seeeed
      - LOOKUP_HOST=lookup
      - LOOKUP_PORT=22000
      - LOGLEVEL=DEBUG
    build: ./Boerse/
    depends_on:
      - lookup
    restart: unless-stopped
  bank:
    environment:
      - LOOKUP_HOST=lookup
      - LOOKUP_PORT=22000
      - LOGLEVEL=INFO
    build: ./Bank/
    depends_on:
      - lookup
      - boerse
    restart: unless-stopped