version: '3.3'
services:
  lookup:
    container_name: lookup
    environment:
      - PORT=22000
      - LOGLEVEL=INFO
    build: ./Lookup/
    ports:
      - 22000:22000
    restart: unless-stopped
    deploy:
      replicas: 1
  boerse:
    environment:
      - PORT=12345
      - LOOKUP_HOST=lookup
      - LOOKUP_PORT=22000
      - LOGLEVEL=DEBUG
    build: ./Boerse/
    depends_on:
      - lookup
    restart: unless-stopped
  bank:
    environment:
      - LOOKUP_HOST=lookup
      - LOOKUP_PORT=22000
      - LOGLEVEL=INFO
      - PORT=22100
    build: ./Bank/
    ports:
      # - 22100:22100
      # - "22100-22199:22100"
      - 22100
      # use - 22100 for random port (this can be used to run multiple instances)
    # ensure that lookup/Börse is started before bank
    depends_on:
      - lookup
      - boerse
    restart: unless-stopped
  # MQTT Broker
  mosquitto:
    container_name: "mosquitto"
    image: "eclipse-mosquitto:2.0.15"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"