#
# Constants
#
LOOKUP_KEEPALIVE_INTERVAL = 30
CLIENT_KEEPALIVE_INTERVAL = 15
RTT_MEASUREMENT_COUNT = 20
MIN_PRICE_CHANGE = -10
MAX_PRICE_CHANGE = 10
MIN_TRADE_AMOUNT = 1
MAX_TRADE_AMOUNT = 100
MIN_PRICE_CHANGE_INTERVAL = 925.0
MAX_PRICE_CHANGE_INTERVAL = 960.0
PRINT_PRICES_INTERVAL = 45
PRINT_PRICES = False